travis:
  secure:
    BINSTAR_TOKEN: Zfopce2Tlm9GkbUJiLKzOfnsaJZmrjc5TUk33rUhdOzAQhwOTMGU9SlYvCiaZ18SgRYCQMszeySngqCXg3k+p1D0suoPGUdbMmHCPvNloAGa4sTQJvOdStAAHL7BsLz3c3NRDJWnO+UXtdoldLQRIbQumhq9IUcLMP0WBJZ+NhF8FPEbTJU93Hrc2peGvXw2MCUvkTcojrgS5DjoIVz56LWd1fcYoYZ+6duigjlqofi9Q2pMEvvdGVgf8oX32B3UAo+i9lHgKFykD165FVRv6B+mEA2SjkweZ08G/VtRaBMA7F1dbfPw4xqUGFzFPgj4PdFNjw3ruQUQ5ESEpNUx0SFGIiGTSJE06XmXKs3DcH8sQGaldLmduSM5/aTSOexfydw/u1tuQQkasMG1v4AR2U5lpZU0HKEBUS5XT681+z14hgGQwM5kcBUAKu5e1JTR1DQrUQhnoalI3YvBAmmvRa9MtdRO7hFyGz9gR1E6FLLMeQ8mDUQMt4h/hJ9z5EG/vw6QBqwzhBXEZwmNk2CFlxDa9ZaSYdSsZItSpAlGhq4R87PdpO4bDcxlFRtCMpHhfzKUgtp73o5Q399oWADn25/lZNW3BLrn80sFv8GqEmSsGcFGhF6Y2P04cyLO+ebnrheSIM0azO3+RKQcYGgiqJWUf1pVZIUx7wPubgGsQbA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
